DROP TABLE IF EXISTS books;

CREATE TABLE books (
  id INT AUTO_INCREMENT PRIMARY KEY,
  barcode VARCHAR(250) UNIQUE NOT NULL,
  name VARCHAR(250) NOT NULL,
  author VARCHAR(250) NOT NULL,
  quantity INT NOT NULL,
  price DECIMAL NOT NULL,
  type ENUM('REGULAR', 'ANTIQUE', 'SCIENCE') NOT NULL,
  release_year INT,
  science_index INT
);